<a href="https://colab.research.google.com/github/rakshajalan/Delving-deep-into-GANs/blob/master/SONY_dschallenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sklearn
import numpy as np
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from pandas.plotting import parallel_coordinates
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
import sys
sys.executable 
import plotly
import plotly.graph_objects as go


In [ ]:
data = pd.read_csv('DataScienceChallenge.csv')

data.drop(['phone number'], axis=1, inplace=True ) #drop unimportant fratures


data['total charge']=data['total day charge']+data['total eve charge']+data['total night charge']+data['total intl charge']


data.columns
data.head(5)

state  account length  area code  ... customer service calls  churn  total charge
0    KS             128        415  ...                      1  False         75.56
1    OH             107        415  ...                      1  False         59.24
2    NJ             137        415  ...                      0  False         62.29
3    OH              84        408  ...                      2  False         66.80
4    OK              75        415  ...                      3  False         52.09

[5 rows x 21 columns]

In [ ]:
print ("Rows     : " ,data.shape[0])
print ("Columns  : " ,data.shape[1])
print ("\nFeatures : \n" ,data.columns.tolist())
print ("\nMissing values :  ", data.isnull().sum().values.sum())
print ("\nUnique values :  \n",data.nunique())

Rows     :  3333
Columns  :  21

Features : 
 ['state', 'account length', 'area code', 'international plan', 'voice mail plan', 'number vmail messages', 'total day minutes', 'total day calls', 'total day charge', 'total eve minutes', 'total eve calls', 'total eve charge', 'total night minutes', 'total night calls', 'total night charge', 'total intl minutes', 'total intl calls', 'total intl charge', 'customer service calls', 'churn', 'total charge']

Missing values :   0

Unique values :  
 state                       51
account length             212
area code                    3
international plan           2
voice mail plan              2
number vmail messages       46
total day minutes         1667
total day calls            119
total day charge          1667
total eve minutes         1611
total eve calls            123
total eve charge          1440
total night minutes       1591
total night calls          120
total night charge         933
total intl minutes         162
total int

In [ ]:
data.describe()


account length    area code  ...  customer service calls  total charge
count     3333.000000  3333.000000  ...             3333.000000   3333.000000
mean       101.064806   437.182418  ...                1.562856     59.449754
std         39.822106    42.371290  ...                1.315491     10.502261
min          1.000000   408.000000  ...                0.000000     22.930000
25%         74.000000   408.000000  ...                1.000000     52.380000
50%        101.000000   415.000000  ...                1.000000     59.470000
75%        127.000000   510.000000  ...                2.000000     66.480000
max        243.000000   510.000000  ...                9.000000     96.150000

[8 rows x 17 columns]

In [ ]:
True_churn=data[data['churn']==True] #statistics of fetures of churned customers
True_churn.describe()

account length   area code  ...  customer service calls  total charge
count      483.000000  483.000000  ...              483.000000    483.000000
mean       102.664596  437.817805  ...                2.229814     65.355963
std         39.467820   42.792270  ...                1.853275     13.885268
min          1.000000  408.000000  ...                0.000000     22.930000
25%         76.000000  408.000000  ...                1.000000     53.425000
50%        103.000000  415.000000  ...                2.000000     66.910000
75%        127.000000  510.000000  ...                4.000000     76.655000
max        225.000000  510.000000  ...                9.000000     96.150000

[8 rows x 17 columns]

In [ ]:
False_churn=data[data['churn']==False] #statistics of fetures of Not churned customers
False_churn.describe()

account length    area code  ...  customer service calls  total charge
count     2850.000000  2850.000000  ...             2850.000000   2850.000000
mean       100.793684   437.074737  ...                1.449825     58.448807
std         39.882350    42.306156  ...                1.163883      9.458436
min          1.000000   408.000000  ...                0.000000     23.250000
25%         73.000000   408.000000  ...                1.000000     52.220000
50%        100.000000   415.000000  ...                1.000000     58.920000
75%        127.000000   510.000000  ...                2.000000     65.137500
max        243.000000   510.000000  ...                8.000000     87.290000

[8 rows x 17 columns]

In [ ]:
data['churn'].value_counts()  #Instances of churns and Not churns  # Data Imbalance


False    2850
True      483
Name: churn, dtype: int64

In [ ]:
#average of total charges for churn and not churn
fig = go.FigureWidget()
grouped_df = data.groupby('churn').mean()
fig.add_bar(x=grouped_df.index, y= grouped_df['total day charge']+grouped_df['total eve charge']+grouped_df['total night charge']);

fig.layout.xaxis.title = 'Churn'
fig.layout.yaxis.title = 'Average Total charge'
fig.layout.title = 'Total charges'
fig.show()

#can be seen that avg total charge of churned customer is more than non-churn customers


In [ ]:
#relation between 
import plotly.express as px
fig = px.violin(data, x='voice mail plan', box=True,color='churn',
          hover_data=data.columns)
fig

#From below violin plot it can be noticed that people with voice mail plan are very unlikely to churn

#This suggests company to in invest in voice mail plans as if customer opt for voice plan he is likely to stay

In [ ]:

import plotly.express as px
fig = px.violin(data, x='international plan', y="total intl minutes", box=True, points="all",color='churn',
          hover_data=data.columns)
fig

#looks like even after opting for  international plan, its still not good for long conversation.
#One strategy to retain customer is  reduce call rates after 12-15 minutes so customer will keep using service 

In [ ]:
import plotly.express as px
fig = px.violin(data, y='customer service calls', x='international plan', box=True, points="all",color='churn',
          hover_data=data.columns)
fig

#if customer has called more than 4 times then he is likely to get churn.
#Active customers do on average 2-3 service calls 

In [ ]:

import plotly.express as px
fig = px.violin(data, x='account length', y='total charge', box=True,color='churn',hover_data=data.columns)
data.drop(['total charge'], axis=1, inplace=True ) #remove total charge feature as we are done with its effect

fig



 #Looks like people having higher charger greater than 80 are more likelt to churn

In [ ]:
#contribution of total day charge in total charge
import plotly.express as px
fig = px.violin(data, y='total day charge', x="account length", box=True,color='churn',
          hover_data=data.columns)
fig



#Total day charge has largest influence on total charge. 
#Inorder to retain customers compancy may focus on better day charge packages. 


In [ ]:
#statewise analysis of churned customers
import plotly.express as px

features=[ 'number vmail messages', 'total day minutes', 'total eve minutes','total night minutes', 'total intl minutes']

import plotly.graph_objects as go
for c in features:
       fig = px.histogram(True_churn, x='state',y=c)
       fig.show()

# import plotly.graph_objects as go
# for c in features:
#        fig = px.histogram(False_churn, x='state',y=c)
#        fig.show()


In [ ]:
#to analyse correlation between variables draw heatmap
fig = go.FigureWidget()
cor_mat = data.corr()
print (cor_mat.columns)
fig.add_heatmap(z=cor_mat, 
                x=cor_mat.columns,
                y=cor_mat.columns,
                showscale=True)
fig.layout.width = 500
fig.layout.height =500
#fig.layout.yaxis.automargin = True
fig.layout.title = 'Feature Heatmap for customer churn '
fig
#Total charges and total minutes are positively correlated so we need to consider only one of them

Index(['account length', 'area code', 'number vmail messages',
       'total day minutes', 'total day calls', 'total day charge',
       'total eve minutes', 'total eve calls', 'total eve charge',
       'total night minutes', 'total night calls', 'total night charge',
       'total intl minutes', 'total intl calls', 'total intl charge',
       'customer service calls', 'churn'],
      dtype='object')


FigureWidget({
    'data': [{'showscale': True,
              'type': 'heatmap',
              'uid': '95c2390…

In [ ]:
  
X = data.iloc[:, 0:19].values 
y = data.iloc[:, -1].values # Churn 
# Encoding categorical data in X 
from sklearn.preprocessing import LabelEncoder 

labelencoder_X_0 = LabelEncoder() 
X[:, 0] = labelencoder_X_0.fit_transform(X[:, 0]) 

labelencoder_X_2 = LabelEncoder() 
X[:, 3] = labelencoder_X_2.fit_transform(X[:, 3]) 

labelencoder_X_1 = LabelEncoder() 
X[:, 2] = labelencoder_X_1.fit_transform(X[:, 2]) 

labelencoder_X_3 = LabelEncoder() 
X[:, 4] = labelencoder_X_3.fit_transform(X[:, 4]) 
# Encoding categorical data in y 

labelencoder_y = LabelEncoder() 
y = labelencoder_y.fit_transform(y) 


In [ ]:
X.shape


(3333, 19)

In [ ]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y,  
                                                     test_size = 0.2,  
                                                    random_state = 0) 
X_train

array([[26, 80, 1, ..., 3, 2.51, 3],
       [38, 28, 1, ..., 3, 2.73, 3],
       [37, 120, 1, ..., 1, 2.59, 2],
       ...,
       [20, 93, 2, ..., 2, 3.0, 1],
       [14, 91, 1, ..., 3, 2.67, 3],
       [27, 130, 0, ..., 2, 4.56, 5]], dtype=object)

In [ ]:

#Feature Scaling 
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler() 
X_train = sc.fit_transform(X_train) 
X_test = sc.transform(X_test) 
# Import RandomForestClassifier 
from sklearn.ensemble import RandomForestClassifier 
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from xgboost import XGBClassifier
#clf=svm.SVC()
clf = RandomForestClassifier(random_state=3) 
#clf=XGBClassifier(seed=10)
# Fit to the training data 
clf.fit(X_train, y_train) 


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=3, verbose=0,
                       warm_start=False)

In [ ]:
y_pred = clf.predict(X_test) 
# Compute accuracy 
from sklearn.metrics import accuracy_score 
print (accuracy_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix 
print(confusion_matrix(y_test, y_pred))

from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

0.9550224887556222
[[568  11]
 [ 19  69]]
              precision    recall  f1-score   support

           0       0.97      0.98      0.97       579
           1       0.86      0.78      0.82        88

    accuracy                           0.96       667
   macro avg       0.92      0.88      0.90       667
weighted avg       0.95      0.96      0.95       667



In [ ]:
data1=data.drop(columns=['churn'])
yy=pd.DataFrame(data1)
yy.columns
col_sorted_by_importance=clf.feature_importances_.argsort()
feat_imp=pd.DataFrame({
    'Important Features RF':yy.columns[col_sorted_by_importance],
    'Imps':clf.feature_importances_[col_sorted_by_importance]
})

fig=px.bar(feat_imp, x='Important Features RF', y='Imps')
fig


In [ ]:
#Feature Scaling 
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler() 
X_train = sc.fit_transform(X_train) 
X_test = sc.transform(X_test) 
# Import RandomForestClassifier 
from sklearn.ensemble import RandomForestClassifier 
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from xgboost import XGBClassifier
#clf=svm.SVC()

clf=XGBClassifier(seed=10)
# Fit to the training data 
clf.fit(X_train, y_train) 
y_pred = clf.predict(X_test) 
# Compute accuracy 
from sklearn.metrics import accuracy_score 
print (accuracy_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix 
print(confusion_matrix(y_test, y_pred))

from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

yy=data.drop(columns=['churn'])

cols=['state','account length', 'area code', 'international plan',
       'voice mail plan', 'number vmail messages', 'total day minutes',
       'total day calls', 'total day charge', 'total eve minutes',
       'total eve calls', 'total eve charge', 'total night minutes',
       'total night calls', 'total night charge', 'total intl minutes',
       'total intl calls', 'total intl charge', 'customer service calls']
col_sorted_by_importance=clf.feature_importances_.argsort()
#print (col_sorted_by_importance)
feat_imp=pd.DataFrame({
    'Important Features XGBoost':yy.columns[col_sorted_by_importance],
    'Imps':clf.feature_importances_[col_sorted_by_importance]
})

fig=px.bar(feat_imp, x='Important Features XGBoost', y='Imps')
fig

0.952023988005997
[[568  11]
 [ 21  67]]
              precision    recall  f1-score   support

           0       0.96      0.98      0.97       579
           1       0.86      0.76      0.81        88

    accuracy                           0.95       667
   macro avg       0.91      0.87      0.89       667
weighted avg       0.95      0.95      0.95       667



In [ ]:
#Remove Correlational and unimportant features

data.drop(['total day charge'], axis=1, inplace=True)
data.drop(['total eve charge'], axis=1, inplace=True)
data.drop(['total night charge'], axis=1, inplace=True)
data.drop(['total intl charge'], axis=1, inplace=True)

X = data.iloc[:, 0:14].values 
y = data.iloc[:, -1].values # Churn 
# Encoding categorical data in X 
from sklearn.preprocessing import LabelEncoder 

labelencoder_X_0 = LabelEncoder() 
X[:, 0] = labelencoder_X_0.fit_transform(X[:, 0]) 

labelencoder_X_2 = LabelEncoder() 
X[:, 3] = labelencoder_X_2.fit_transform(X[:, 3]) 

labelencoder_X_1 = LabelEncoder() 
X[:, 2] = labelencoder_X_1.fit_transform(X[:, 2]) 

labelencoder_X_3 = LabelEncoder() 
X[:, 4] = labelencoder_X_3.fit_transform(X[:, 4]) 
# Encoding categorical data in y 

labelencoder_y = LabelEncoder() 
y = labelencoder_y.fit_transform(y) 


from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y,  test_size = 0.2, random_state = 0) 
#Feature Scaling 
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler() 
X_train = sc.fit_transform(X_train) 
X_test = sc.transform(X_test) 
# Import RandomForestClassifier 
from sklearn.ensemble import RandomForestClassifier 
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from xgboost import XGBClassifier
#clf=svm.SVC()

clf=XGBClassifier(seed=10)
# Fit to the training data 
#clf=svm.SVC()

clf = RandomForestClassifier(random_state=3) 
clf.fit(X_train, y_train) 
y_pred = clf.predict(X_test) 
# Compute accuracy 
from sklearn.metrics import accuracy_score 
print (accuracy_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix 
print(confusion_matrix(y_test, y_pred))

from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

yy=data.drop(columns=['churn'])


col_sorted_by_importance=clf.feature_importances_.argsort()
#print (col_sorted_by_importance)
feat_imp=pd.DataFrame({
    'Important Features RF':yy.columns[col_sorted_by_importance],
    'Imps':clf.feature_importances_[col_sorted_by_importance]
})

fig=px.bar(feat_imp, x='Important Features RF', y='Imps')
fig

0.9340329835082459
[[576   3]
 [ 41  47]]
              precision    recall  f1-score   support

           0       0.93      0.99      0.96       579
           1       0.94      0.53      0.68        88

    accuracy                           0.93       667
   macro avg       0.94      0.76      0.82       667
weighted avg       0.93      0.93      0.93       667

